import React, { useState } from 'react';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { CreditReport } from '@/pages/Index';
import { Download, Calendar, Building, TrendingUp, AlertTriangle, MessageSquare, BarChart3 } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';

interface ReportDisplayProps {
  report: CreditReport;
}

type SectionTitle = 'Company Overview' | 'Financial Highlights' | 'Key Risks' | 'Management Commentary';

export const ReportDisplay: React.FC<ReportDisplayProps> = ({ report }) => {
  const [activeSection, setActiveSection] = useState<SectionTitle>('Company Overview');
  const { toast } = useToast();

  if (!report || !report.companyName) {
    return <div>No report data available.</div>;
  }

  const handleDownload = () => {
    const reportContent = `
FINANCIAL ANALYSIS REPORT: ${report.companyName.toUpperCase()}

Generated on: ${new Date(report.generatedAt).toLocaleDateString()}

===============================================

COMPANY OVERVIEW
${report.overview}

FINANCIAL HIGHLIGHTS
${report.financialHighlights}

KEY RISKS
${report.keyRisks}

MANAGEMENT COMMENTARY
${report.managementCommentary}

===============================================
Generated by FinancialLLM Analyzer
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${report.companyName.replace(/[^a-z0-9]/gi, '_')}_financial_analysis.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast({
      title: "Report downloaded",
      description: "Your financial analysis report has been saved as a text file.",
    });
  };

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  const sections = [
    {
      title: 'Company Overview' as SectionTitle,
      content: report.overview,
      icon: Building,
      bgColor: 'bg-blue-50',
      borderColor: 'border-blue-200',
      iconBg: 'bg-blue-100',
      iconColor: 'text-blue-600',
      titleColor: 'text-blue-900',
      description: 'Business model and strategic positioning analysis'
    },
    {
      title: 'Financial Highlights' as SectionTitle,
      content: report.financialHighlights,
      icon: BarChart3,
      bgColor: 'bg-green-50',
      borderColor: 'border-green-200',
      iconBg: 'bg-green-100',
      iconColor: 'text-green-600',
      titleColor: 'text-green-900',
      description: 'Key financial metrics and performance indicators'
    },
    {
      title: 'Key Risks' as SectionTitle,
      content: report.keyRisks,
      icon: AlertTriangle,
      bgColor: 'bg-red-50',
      borderColor: 'border-red-200',
      iconBg: 'bg-red-100',
      iconColor: 'text-red-600',
      titleColor: 'text-red-900',
      description: 'Identified business, financial, and market risk factors'
    },
    {
      title: 'Management Commentary' as SectionTitle,
      content: report.managementCommentary,
      icon: MessageSquare,
      bgColor: 'bg-purple-50',
      borderColor: 'border-purple-200',
      iconBg: 'bg-purple-100',
      iconColor: 'text-purple-600',
      titleColor: 'text-purple-900',
      description: 'Executive insights and strategic outlook'
    }
  ];

  const getButtonClass = (sectionTitle: SectionTitle) => {
    const isActive = activeSection === sectionTitle;
    const baseClass = "py-2 px-4 rounded-lg font-semibold transition-all duration-300 ease-in-out shadow-md flex items-center justify-center text-sm";

    if (isActive) {
      const activeColors = {
        'Company Overview': 'bg-blue-600 text-white',
        'Financial Highlights': 'bg-green-600 text-white',
        'Key Risks': 'bg-red-600 text-white',
        'Management Commentary': 'bg-purple-600 text-white',
      };
      return `${baseClass} ${activeColors[sectionTitle]} scale-105`;
    }

    const inactiveColors = {
        'Company Overview': 'bg-white hover:bg-blue-100 text-blue-800',
        'Financial Highlights': 'bg-white hover:bg-green-100 text-green-800',
        'Key Risks': 'bg-white hover:bg-red-100 text-red-800',
        'Management Commentary': 'bg-white hover:bg-purple-100 text-purple-800',
      };
    return `${baseClass} ${inactiveColors[sectionTitle]}`;
  };
  
  const activeSectionData = sections.find(s => s.title === activeSection);

  return (
    <div className="space-y-8">
      {/* Report Header */}
      <Card className="p-6 bg-gradient-to-r from-blue-50 via-indigo-50 to-purple-50 border-blue-200 shadow-lg">
        <div className="flex items-center justify-between">
          <div className="space-y-2">
            <div className="flex items-center space-x-3">
              <div className="bg-blue-600 p-2 rounded-lg">
                <TrendingUp className="h-6 w-6 text-white" />
              </div>
              <div>
                <h1 className="text-2xl font-bold text-slate-900">{report.companyName}</h1>
                <p className="text-base text-slate-600 font-medium">Financial Analysis Report</p>
              </div>
            </div>
            <div className="flex items-center space-x-4 text-sm text-slate-600 pl-1">
              <div className="flex items-center space-x-1.5">
                <Calendar className="h-4 w-4" />
                <span className="font-medium">{formatDate(report.generatedAt)}</span>
              </div>
              <Badge variant="secondary" className="bg-green-100 text-green-800 px-3 py-1">
                LLM Generated Analysis
              </Badge>
            </div>
          </div>
          
          <Button onClick={handleDownload} className="bg-blue-600 hover:bg-blue-700 px-4 py-2 text-sm font-medium">
            <Download className="mr-2 h-4 w-4" />
            Download Report
          </Button>
        </div>
      </Card>

      {/* Section Buttons */}
      <Card className="p-3 bg-slate-50 shadow-md">
        <div className="flex justify-center space-x-3">
          {sections.map(section => (
            <button
              key={section.title}
              onClick={() => setActiveSection(section.title)}
              className={getButtonClass(section.title)}
            >
              <section.icon className="mr-2 h-5 w-5" />
              <span>{section.title}</span>
            </button>
          ))}
        </div>
      </Card>
      
      {/* Report Sections */}
        <div className="grid gap-8">
          <Card 
             className={`p-8 ${activeSectionData?.bgColor} ${activeSectionData?.borderColor} border-2 hover:shadow-xl transition-all duration-300 hover:scale-[1.02]`}
           >
             <div className="space-y-6">
               {/* Section Header */}
               <div className="flex items-start justify-between">
                 <div className="flex items-center space-x-4">
                   <div className={`p-4 rounded-xl ${activeSectionData?.iconBg} shadow-md`}>
                     {activeSectionData && <activeSectionData.icon className={`h-7 w-7 ${activeSectionData?.iconColor}`} />}
                   </div>
                   <div>
                     <h2 className={`text-2xl font-bold ${activeSectionData?.titleColor}`}>
                       {activeSectionData?.title}
                     </h2>
                     <p className="text-slate-600 text-sm font-medium mt-1">
                       {activeSectionData?.description}
                     </p>
                   </div>
                 </div>
               </div>
               
               {/* Section Content */}
                 <div className="bg-white/80 rounded-lg p-6 shadow-sm border border-white/50">
                   <div className="prose prose-slate max-w-none prose-sm whitespace-pre-wrap">
                    {activeSectionData?.content}
                   </div>
                 </div>
             </div>
           </Card>
        </div>
    </div>
  );
};
