import React, { useState } from 'react';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Download } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import type { CreditReport } from '@/types';
import { REPORT_SECTIONS } from '@/constants/reportSections';

interface ReportDisplayProps {
  report: CreditReport;
}

export const ReportDisplay: React.FC<ReportDisplayProps> = ({ report }) => {
  const [activeKey, setActiveKey] = useState(REPORT_SECTIONS[0].key);
  const { toast } = useToast();

  if (!report?.companyName) {
    return <div className="text-slate-500 py-8 text-center">No report data available.</div>;
  }

  const handleDownload = () => {
    const parts = [
      `FINANCIAL ANALYSIS REPORT: ${report.companyName.toUpperCase()}`,
      `Generated on: ${new Date(report.generatedAt).toLocaleDateString()}`,
      '===============================================',
      ...REPORT_SECTIONS.map(
        (s) => `${s.title.toUpperCase()}\n${report[s.key] ?? ''}`
      ),
      '===============================================',
      'Generated by FinancialLLM Analyzer',
    ];
    const blob = new Blob([parts.join('\n\n')], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${report.companyName.replace(/[^a-z0-9]/gi, '_')}_analysis.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast({ title: 'Downloaded', description: 'Report saved as text file.' });
  };

  const activeSection = REPORT_SECTIONS.find((s) => s.key === activeKey);
  const activeContent = activeSection ? (report[activeSection.key] ?? '') : '';

  return (
    <div className="space-y-4">
      {/* Section tabs */}
      <div className="flex flex-wrap gap-2">
        {REPORT_SECTIONS.map((section) => {
          const Icon = section.icon;
          const isActive = activeKey === section.key;
          return (
            <button
              key={section.key}
              onClick={() => setActiveKey(section.key)}
              className={`flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm font-medium transition-all ${
                isActive
                  ? 'bg-slate-800 text-white shadow-md'
                  : 'bg-white text-slate-600 hover:bg-slate-100 border border-slate-200'
              }`}
            >
              <Icon className="h-4 w-4" />
              <span className="hidden sm:inline">{section.title}</span>
            </button>
          );
        })}
      </div>

      {/* Section content */}
      {activeSection && (
        <Card className="rounded-xl border border-slate-200 bg-white shadow-sm overflow-hidden">
          <div className="p-5 border-b border-slate-100 bg-slate-50/50">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className={`p-2 rounded-lg ${activeSection.iconBg}`}>
                  <activeSection.icon className={`h-5 w-5 ${activeSection.iconColor}`} />
                </div>
                <div>
                  <h3 className="font-semibold text-slate-900">{activeSection.title}</h3>
                  <p className="text-xs text-slate-500">{activeSection.description}</p>
                </div>
              </div>
              <Button
                onClick={handleDownload}
                variant="outline"
                size="sm"
                className="hidden sm:flex border-slate-200 text-slate-600 hover:bg-slate-100"
              >
                <Download className="h-4 w-4 mr-1.5" />
                Export
              </Button>
            </div>
          </div>
          <div className="p-5 max-h-[32rem] overflow-y-auto">
            {activeContent.trim() ? (
              <div className="prose prose-slate prose-sm max-w-none whitespace-pre-wrap text-slate-700 leading-relaxed">
                {activeContent}
              </div>
            ) : (
              <p className="text-slate-400 italic text-sm">No content available for this section.</p>
            )}
          </div>
        </Card>
      )}
    </div>
  );
};
