import './Index.css';
import React, { useState, useCallback } from 'react';
import { FileUpload } from '@/components/FileUpload';
import { ReportDisplay } from '@/components/ReportDisplay';
import { ChatInterface } from '@/components/ChatInterface';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import {
  FileText,
  TrendingUp,
  Shield,
  Users,
  Zap,
  Calendar,
  Download,
  RotateCcw,
  MessageCircle,
} from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import type { CreditReport, ReportSectionKey } from '@/types';
import { REPORT_SECTIONS } from '@/constants/reportSections';
import {
  uploadDocument,
  generateReport,
  fetchPdfFromUrl,
  askQuestion as apiAskQuestion,
} from '@/lib/api';

/* ------------------------------------------------------------------ */
/*  Types                                                              */
/* ------------------------------------------------------------------ */

type ActiveView = ReportSectionKey | 'chat';

/* ------------------------------------------------------------------ */
/*  Component                                                          */
/* ------------------------------------------------------------------ */

const Index = () => {
  const [generatedReport, setGeneratedReport] = useState<CreditReport | null>(null);
  const [isUploading, setIsUploading] = useState(false);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [sessionFilename, setSessionFilename] = useState<string | null>(null);
  const [activeView, setActiveView] = useState<ActiveView>('overview');
  const { toast } = useToast();

  /* ── Handlers ── */

  const handleAnalyze = async (file: File) => {
    setIsAnalyzing(true);
    toast({
      title: 'Analysis started',
      description: 'Uploading and analyzing the document. This may take a few minutes.',
    });
    try {
      const { filename } = await uploadDocument(file);
      const report = await generateReport(filename);
      setGeneratedReport(report);
      setSessionFilename(filename);
      setActiveView('overview');
      toast({ title: 'Analysis complete', description: 'Your report has been generated.' });
    } catch (err) {
      console.error('Analyze error:', err);
      toast({
        title: 'Analysis failed',
        description: err instanceof Error ? err.message : 'Something went wrong.',
        variant: 'destructive',
      });
    } finally {
      setIsAnalyzing(false);
    }
  };

  const handleUrlSubmit = async (url: string) => {
    setIsUploading(true);
    try {
      const blob = await fetchPdfFromUrl(url);
      const fileName = url.substring(url.lastIndexOf('/') + 1) || 'report.pdf';
      const file = new File([blob], fileName, { type: 'application/pdf' });
      await handleAnalyze(file);
    } catch (err) {
      toast({
        title: 'Error',
        description: err instanceof Error ? err.message : 'Failed to fetch PDF.',
        variant: 'destructive',
      });
    } finally {
      setIsUploading(false);
    }
  };

  const resetApplication = () => {
    setGeneratedReport(null);
    setIsUploading(false);
    setIsAnalyzing(false);
    setSessionFilename(null);
    setActiveView('overview');
  };

  const handleAskQuestion = async (question: string): Promise<string> => {
    if (!generatedReport || !sessionFilename) {
      return 'Cannot ask questions until a report has been generated.';
    }
    try {
      return await apiAskQuestion({
        filename: sessionFilename,
        question,
        companyName: generatedReport.companyName,
      });
    } catch (err) {
      console.error('Error answering question:', err);
      return err instanceof Error ? err.message : 'An unexpected error occurred.';
    }
  };

  const handleDownload = useCallback(() => {
    if (!generatedReport) return;
    const divider = '═'.repeat(56);
    const sectionDivider = '─'.repeat(40);
    const parts = [
      'FINANCIAL ANALYSIS REPORT',
      `Company: ${generatedReport.companyName}`,
      `Generated: ${new Date(generatedReport.generatedAt).toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      })}`,
      divider,
      ...REPORT_SECTIONS.map(
        (s) =>
          `\n${sectionDivider}\n${s.title.toUpperCase()}\n${s.description}\n${sectionDivider}\n\n${generatedReport[s.key] ?? 'N/A'}`
      ),
      `\n${divider}`,
      'Generated by FinancialLLM Analyzer',
    ];
    const blob = new Blob([parts.join('\n')], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${generatedReport.companyName.replace(/[^a-z0-9]/gi, '_')}_analysis.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast({ title: 'Downloaded', description: 'Report saved as text file.' });
  }, [generatedReport, toast]);

  /* ── Landing page (no report) ── */

  if (!generatedReport) {
    return (
      <div className="page">
        <header className="header">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-5">
            <div className="flex items-center gap-4">
              <div className="bg-slate-800 p-2.5 rounded-xl shadow-sm">
                <TrendingUp className="h-6 w-6 text-amber-400" />
              </div>
              <div>
                <h1 className="text-xl sm:text-2xl font-bold tracking-tight text-slate-900">
                  FinancialLLM Analyzer
                </h1>
                <p className="text-sm text-slate-500 mt-0.5">
                  Document intelligence with RAG
                </p>
              </div>
            </div>
          </div>
        </header>

        <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10 sm:py-12 min-h-[16rem]">
          <div className="text-center space-y-12">
            <div className="space-y-5 max-w-3xl mx-auto">
              <h2 className="text-3xl sm:text-4xl lg:text-5xl font-bold text-slate-900 leading-tight tracking-tight">
                Transform financial documents into{' '}
                <span className="bg-gradient-to-r from-blue-600 to-indigo-600 bg-clip-text text-transparent">
                  actionable insights
                </span>
              </h2>
              <p className="text-lg sm:text-xl text-slate-600 leading-relaxed">
                Analyze 10-Ks, quarterly reports, SEC filings, and earnings
                materials with AI-powered analysis and Q&A.
              </p>
            </div>

            <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-5 max-w-6xl mx-auto">
              {[
                { icon: FileText, bg: 'bg-slate-100', color: 'text-slate-700', title: 'Document processing', desc: 'Quarterly reports, SEC filings, 10-K/10-Q, earnings transcripts' },
                { icon: Zap, bg: 'bg-emerald-50', color: 'text-emerald-600', title: 'LLM + RAG analysis', desc: 'Semantic search and structured sections from your documents' },
                { icon: Shield, bg: 'bg-amber-50', color: 'text-amber-600', title: 'Risk assessment', desc: 'Business, financial, and market risks identified and summarized' },
                { icon: Users, bg: 'bg-violet-50', color: 'text-violet-600', title: 'Executive insights', desc: 'Management commentary and strategic direction' },
              ].map((f) => (
                <Card key={f.title} className="feature-card text-center space-y-4 bg-white/90 backdrop-blur-sm">
                  <div className={`${f.bg} p-3.5 rounded-2xl w-fit mx-auto`}>
                    <f.icon className={`h-6 w-6 ${f.color}`} />
                  </div>
                  <h3 className="text-base font-semibold text-slate-900">{f.title}</h3>
                  <p className="text-sm text-slate-600 leading-relaxed">{f.desc}</p>
                </Card>
              ))}
            </div>

            <div className="max-w-2xl mx-auto">
              <FileUpload
                onAnalyze={handleAnalyze}
                onUrlSubmit={handleUrlSubmit}
                isAnalyzing={isAnalyzing}
                isLoading={isUploading}
              />
            </div>
          </div>
        </main>

        <footer className="header mt-24">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10 text-center">
            <p className="text-slate-500 text-sm">
              Powered by{' '}
              <strong className="text-slate-700">FinancialLLM Analyzer</strong>
              <span className="hidden sm:inline">
                {' '}— Document intelligence with RAG
              </span>
            </p>
          </div>
        </footer>
      </div>
    );
  }

  /* ── Dashboard layout (report generated) ── */

  const reportDate = new Date(generatedReport.generatedAt).toLocaleDateString(
    'en-US',
    { month: 'short', day: 'numeric', year: 'numeric' }
  );

  return (
    <div className="h-screen flex flex-col bg-slate-50">
      {/* ── Compact header ── */}
      <header className="shrink-0 bg-white border-b border-slate-200 shadow-sm z-10">
        <div className="px-4 sm:px-6 h-14 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="bg-slate-800 p-1.5 rounded-lg">
              <TrendingUp className="h-4 w-4 text-amber-400" />
            </div>
            <h1 className="text-sm font-bold tracking-tight text-slate-900">
              FinancialLLM Analyzer
            </h1>
          </div>
          {/* Company name on mobile (sidebar hides it) */}
          <p className="lg:hidden text-sm font-semibold text-slate-700 truncate max-w-[180px]">
            {generatedReport.companyName}
          </p>
        </div>
      </header>

      {/* ── Sidebar + Content ── */}
      <div className="flex-1 flex overflow-hidden">
        {/* ── Sidebar ── */}
        <aside className="sidebar-panel w-16 lg:w-64 shrink-0 border-r border-slate-200 bg-white flex flex-col">
          {/* Company info */}
          <div className="p-3 lg:p-5 border-b border-slate-100">
            <div className="hidden lg:block">
              <h2 className="font-bold text-slate-900 text-base truncate">
                {generatedReport.companyName}
              </h2>
              <div className="flex items-center gap-2 mt-1.5 flex-wrap">
                <span className="text-xs text-slate-500">Analysis Report</span>
                <span className="text-slate-300">·</span>
                <span className="text-xs text-slate-400 inline-flex items-center gap-1">
                  <Calendar className="h-3 w-3" />
                  {reportDate}
                </span>
              </div>
            </div>
            {/* Mobile: company icon */}
            <div className="lg:hidden flex justify-center">
              <div className="bg-slate-800 p-2 rounded-lg">
                <TrendingUp className="h-4 w-4 text-amber-400" />
              </div>
            </div>
          </div>

          {/* Section nav */}
          <nav className="flex-1 p-2 lg:p-3 space-y-1 overflow-y-auto">
            <p className="hidden lg:block px-3 pt-1 pb-2 text-[0.65rem] font-semibold uppercase tracking-widest text-slate-400">
              Report
            </p>

            {REPORT_SECTIONS.map((section) => {
              const Icon = section.icon;
              const isActive = activeView === section.key;

              return (
                <button
                  key={section.key}
                  onClick={() => setActiveView(section.key)}
                  title={section.title}
                  className={`
                    sidebar-item w-full flex items-center gap-3
                    px-2 lg:px-3 py-2.5 rounded-lg text-sm font-medium
                    transition-all duration-150
                    ${
                      isActive
                        ? 'bg-slate-100 text-slate-900'
                        : 'text-slate-500 hover:text-slate-700 hover:bg-slate-50'
                    }
                  `}
                >
                  <div
                    className={`p-1.5 rounded-lg shrink-0 transition-colors duration-150 ${
                      isActive ? section.iconBg : ''
                    }`}
                  >
                    <Icon
                      className={`h-4 w-4 ${
                        isActive ? section.iconColor : 'text-slate-400'
                      }`}
                    />
                  </div>
                  <span className="hidden lg:inline truncate">
                    {section.title}
                  </span>
                  {isActive && (
                    <span
                      className={`hidden lg:block ml-auto w-1.5 h-1.5 rounded-full ${section.bulletColor}`}
                    />
                  )}
                </button>
              );
            })}

            {/* Divider */}
            <div className="!my-3 mx-2 border-t border-slate-100" />

            {/* Chat nav item */}
            <button
              onClick={() => setActiveView('chat')}
              title="Ask Questions"
              className={`
                sidebar-item w-full flex items-center gap-3
                px-2 lg:px-3 py-2.5 rounded-lg text-sm font-medium
                transition-all duration-150
                ${
                  activeView === 'chat'
                    ? 'bg-slate-100 text-slate-900'
                    : 'text-slate-500 hover:text-slate-700 hover:bg-slate-50'
                }
              `}
            >
              <div
                className={`p-1.5 rounded-lg shrink-0 transition-colors duration-150 ${
                  activeView === 'chat' ? 'bg-indigo-100' : ''
                }`}
              >
                <MessageCircle
                  className={`h-4 w-4 ${
                    activeView === 'chat' ? 'text-indigo-600' : 'text-slate-400'
                  }`}
                />
              </div>
              <span className="hidden lg:inline">Ask Questions</span>
            </button>
          </nav>

          {/* Bottom actions */}
          <div className="p-2 lg:p-3 border-t border-slate-100 space-y-1.5">
            <Button
              onClick={handleDownload}
              variant="outline"
              size="sm"
              className="w-full justify-center lg:justify-start gap-2 border-slate-200 text-slate-600 hover:bg-slate-50"
            >
              <Download className="h-4 w-4 shrink-0" />
              <span className="hidden lg:inline">Export Report</span>
            </Button>
            <Button
              onClick={resetApplication}
              variant="ghost"
              size="sm"
              className="w-full justify-center lg:justify-start gap-2 text-slate-500 hover:text-slate-700"
            >
              <RotateCcw className="h-4 w-4 shrink-0" />
              <span className="hidden lg:inline">New Analysis</span>
            </Button>
          </div>
        </aside>

        {/* ── Main content ── */}
        <main className="flex-1 overflow-hidden p-4 sm:p-6 lg:p-8">
          {activeView === 'chat' ? (
            <div className="max-w-3xl mx-auto h-full flex flex-col">
              <ChatInterface
                companyName={generatedReport.companyName}
                onAskQuestion={handleAskQuestion}
              />
            </div>
          ) : (
            <div className="max-w-4xl mx-auto overflow-y-auto h-full">
              <ReportDisplay
                report={generatedReport}
                sectionKey={activeView}
              />
            </div>
          )}
        </main>
      </div>
    </div>
  );
};

export default Index;
